fail_fast: false

exclude: >
  (?x)^(
    _build/|
    _tmp/|
    build/|
    output/|
    result/|
    trees/stt/autogen/|
    .*/MAlonzo/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: file-contents-sorter
        name: Sort codespell dictionary and ignore files
        files: ^\.codespell/(dictionary|ignore)\.txt$
        args: [--unique]

  - repo: https://github.com/sirosen/texthooks
    rev: 0.7.1
    hooks:
      - id: fix-spaces

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Spellcheck with codespell
        pass_filenames: false
        args:
          [
            '--config',
            '.codespellrc',
            '--builtin',
            'clear,rare,informal,usage,code,names',
            '--ignore-words',
            '.codespell/ignore.txt',
            '--dictionary',
            '.codespell/dictionary.txt,-',
            '.',
          ]
