fail_fast: false

exclude: >
  (?x)^(
    _build/|
    _tmp/|
    build/|
    output/|
    result/|
    trees/stt/autogen/|
    .*/MAlonzo/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: file-contents-sorter
        name: Sort codespell dictionary and ignore files
        files: ^\.codespell/(dictionary|ignore)\.txt$
        args: [--unique]

  - repo: https://github.com/sirosen/texthooks
    rev: 0.7.1
    hooks:
      - id: fix-spaces

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Spellcheck with codespell
        pass_filenames: false
        args:
          [
            '--config',
            '.codespellrc',
            '--builtin',
            'clear,rare,informal,usage,code,names',
            '--ignore-words',
            '.codespell/ignore.txt',
            '--dictionary',
            '.codespell/dictionary.txt,-',
            '.',
          ]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args:
          [
            '-d',
            '{extends: relaxed, rules: {line-length: disable}}',
          ]
        files: ^(\.github/workflows/.+\.ya?ml|\.pre-commit-config\.yaml)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013]
        files: ^README\.md$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt

  - repo: https://github.com/NixOS/nixfmt
    rev: v1.2.0
    hooks:
      - id: nixfmt
        exclude: ^nix/.+/thunk\.nix$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-format
        files: ^scripts/.+\.py$
