name: Codespell

on:
  push:
    branches-ignore:
      - main
      - benchmark-data
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main') }}

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: pip
          cache-dependency-path: .codespell/requirements.txt

      - name: Install codespell
        run: python -m pip install --upgrade pip -r .codespell/requirements.txt

      - name: Run codespell
        run: |
          codespell \
            --config .codespellrc \
            --skip './trees/ref' \
            --builtin clear,rare,informal,usage,code,names \
            --ignore-words .codespell/ignore.txt \
            --dictionary .codespell/dictionary.txt,-
